/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

#include <stdint.h>
#include "iMX6DQP_registers.h"

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif


/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* SD2_DAT0 (coord A22), CHG_CAPGOOD */
#define BOARD_INITPINS_CHG_CAPGOOD_GPIO                                    GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_CHG_CAPGOOD_GPIO_PIN                                  15U   /*!< GPIO1 pin index: 15 */
#define BOARD_INITPINS_CHG_CAPGOOD_PIN_NAME                             SD2_DAT0   /*!< Pin name */
#define BOARD_INITPINS_CHG_CAPGOOD_LABEL                           "CHG_CAPGOOD"   /*!< Label */
#define BOARD_INITPINS_CHG_CAPGOOD_NAME                            "CHG_CAPGOOD"   /*!< Identifier name */
#define BOARD_INITPINS_CHG_CAPGOOD_DIRECTION             kPIN_MUX_DirectionInput   /*!< Direction */

/* SD2_DAT2 (coord A23), CHG_ENABLE */
#define BOARD_INITPINS_CHG_ENABLE_GPIO                                     GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_CHG_ENABLE_GPIO_PIN                                   13U   /*!< GPIO1 pin index: 13 */
#define BOARD_INITPINS_CHG_ENABLE_PIN_NAME                              SD2_DAT2   /*!< Pin name */
#define BOARD_INITPINS_CHG_ENABLE_LABEL                             "CHG_ENABLE"   /*!< Label */
#define BOARD_INITPINS_CHG_ENABLE_NAME                              "CHG_ENABLE"   /*!< Identifier name */
#define BOARD_INITPINS_CHG_ENABLE_DIRECTION             kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_2 (coord T1), CHG_PFW */
#define BOARD_INITPINS_CHG_PFW_GPIO                                        GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_CHG_PFW_GPIO_PIN                                       2U   /*!< GPIO1 pin index: 2 */
#define BOARD_INITPINS_CHG_PFW_PIN_NAME                                   GPIO_2   /*!< Pin name */
#define BOARD_INITPINS_CHG_PFW_LABEL                                   "CHG_PFW"   /*!< Label */
#define BOARD_INITPINS_CHG_PFW_NAME                                    "CHG_PFW"   /*!< Identifier name */
#define BOARD_INITPINS_CHG_PFW_DIRECTION                 kPIN_MUX_DirectionInput   /*!< Direction */

/* EIM_D29 (coord J19), PMIC_INT_B */
#define BOARD_INITPINS_PMIC_INT_B_GPIO                                     GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_PMIC_INT_B_GPIO_PIN                                   29U   /*!< GPIO3 pin index: 29 */
#define BOARD_INITPINS_PMIC_INT_B_PIN_NAME                               EIM_D29   /*!< Pin name */
#define BOARD_INITPINS_PMIC_INT_B_LABEL                             "PMIC_INT_B"   /*!< Label */
#define BOARD_INITPINS_PMIC_INT_B_NAME                              "PMIC_INT_B"   /*!< Identifier name */
#define BOARD_INITPINS_PMIC_INT_B_DIRECTION              kPIN_MUX_DirectionInput   /*!< Direction */

/* DISP0_DAT18 (coord V25), EN_PMIC_I2C */
#define BOARD_INITPINS_EN_PMIC_I2C_GPIO                                    GPIO5   /*!< GPIO device name: GPIO5 */
#define BOARD_INITPINS_EN_PMIC_I2C_GPIO_PIN                                  12U   /*!< GPIO5 pin index: 12 */
#define BOARD_INITPINS_EN_PMIC_I2C_PIN_NAME                          DISP0_DAT18   /*!< Pin name */
#define BOARD_INITPINS_EN_PMIC_I2C_LABEL                           "EN_PMIC_I2C"   /*!< Label */
#define BOARD_INITPINS_EN_PMIC_I2C_NAME                            "EN_PMIC_I2C"   /*!< Identifier name */
#define BOARD_INITPINS_EN_PMIC_I2C_DIRECTION            kPIN_MUX_DirectionOutput   /*!< Direction */

/* NANDF_D0 (coord A18), LED90 */
#define BOARD_INITPINS_LED90_GPIO                                          GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_LED90_GPIO_PIN                                         0U   /*!< GPIO2 pin index: 0 */
#define BOARD_INITPINS_LED90_PIN_NAME                                   NANDF_D0   /*!< Pin name */
#define BOARD_INITPINS_LED90_LABEL                                       "LED90"   /*!< Label */
#define BOARD_INITPINS_LED90_NAME                                        "LED90"   /*!< Identifier name */
#define BOARD_INITPINS_LED90_DIRECTION                  kPIN_MUX_DirectionOutput   /*!< Direction */

/* NANDF_D1 (coord C17), LED91 */
#define BOARD_INITPINS_LED91_GPIO                                          GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_LED91_GPIO_PIN                                         1U   /*!< GPIO2 pin index: 1 */
#define BOARD_INITPINS_LED91_PIN_NAME                                   NANDF_D1   /*!< Pin name */
#define BOARD_INITPINS_LED91_LABEL                                       "LED91"   /*!< Label */
#define BOARD_INITPINS_LED91_NAME                                        "LED91"   /*!< Identifier name */
#define BOARD_INITPINS_LED91_DIRECTION                  kPIN_MUX_DirectionOutput   /*!< Direction */

/* NANDF_D2 (coord F16), LED92 */
#define BOARD_INITPINS_LED92_GPIO                                          GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_LED92_GPIO_PIN                                         2U   /*!< GPIO2 pin index: 2 */
#define BOARD_INITPINS_LED92_PIN_NAME                                   NANDF_D2   /*!< Pin name */
#define BOARD_INITPINS_LED92_LABEL                                       "LED92"   /*!< Label */
#define BOARD_INITPINS_LED92_NAME                                        "LED92"   /*!< Identifier name */
#define BOARD_INITPINS_LED92_DIRECTION                  kPIN_MUX_DirectionOutput   /*!< Direction */

/* NANDF_D3 (coord D17), LED93 */
#define BOARD_INITPINS_LED93_GPIO                                          GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_LED93_GPIO_PIN                                         3U   /*!< GPIO2 pin index: 3 */
#define BOARD_INITPINS_LED93_PIN_NAME                                   NANDF_D3   /*!< Pin name */
#define BOARD_INITPINS_LED93_LABEL                                       "LED93"   /*!< Label */
#define BOARD_INITPINS_LED93_NAME                                        "LED93"   /*!< Identifier name */
#define BOARD_INITPINS_LED93_DIRECTION                  kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_1 (coord T4), USB_OTG_ID */
#define BOARD_INITPINS_USB_OTG_ID_GPIO                                     GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_USB_OTG_ID_GPIO_PIN                                    1U   /*!< GPIO1 pin index: 1 */
#define BOARD_INITPINS_USB_OTG_ID_PIN_NAME                                GPIO_1   /*!< Pin name */
#define BOARD_INITPINS_USB_OTG_ID_LABEL                             "USB_OTG_ID"   /*!< Label */
#define BOARD_INITPINS_USB_OTG_ID_NAME                              "USB_OTG_ID"   /*!< Identifier name */
#define BOARD_INITPINS_USB_OTG_ID_DIRECTION              kPIN_MUX_DirectionInput   /*!< Direction */

/* CSI0_DAT4 (coord N1), CAM1_TRIG */
#define BOARD_INITPINS_CAM1_TRIG_GPIO                                      GPIO5   /*!< GPIO device name: GPIO5 */
#define BOARD_INITPINS_CAM1_TRIG_GPIO_PIN                                    22U   /*!< GPIO5 pin index: 22 */
#define BOARD_INITPINS_CAM1_TRIG_PIN_NAME                              CSI0_DAT4   /*!< Pin name */
#define BOARD_INITPINS_CAM1_TRIG_LABEL                               "CAM1_TRIG"   /*!< Label */
#define BOARD_INITPINS_CAM1_TRIG_NAME                                "CAM1_TRIG"   /*!< Identifier name */
#define BOARD_INITPINS_CAM1_TRIG_DIRECTION              kPIN_MUX_DirectionOutput   /*!< Direction */

/* CSI0_DAT5 (coord P2), CAM1_STRB */
#define BOARD_INITPINS_CAM1_STRB_GPIO                                      GPIO5   /*!< GPIO device name: GPIO5 */
#define BOARD_INITPINS_CAM1_STRB_GPIO_PIN                                    23U   /*!< GPIO5 pin index: 23 */
#define BOARD_INITPINS_CAM1_STRB_PIN_NAME                              CSI0_DAT5   /*!< Pin name */
#define BOARD_INITPINS_CAM1_STRB_LABEL                               "CAM1_STRB"   /*!< Label */
#define BOARD_INITPINS_CAM1_STRB_NAME                                "CAM1_STRB"   /*!< Identifier name */
#define BOARD_INITPINS_CAM1_STRB_DIRECTION              kPIN_MUX_DirectionOutput   /*!< Direction */

/* CSI0_DAT6 (coord N4), CAM1_RST_n */
#define BOARD_INITPINS_CAM1_RST_n_GPIO                                     GPIO5   /*!< GPIO device name: GPIO5 */
#define BOARD_INITPINS_CAM1_RST_n_GPIO_PIN                                   24U   /*!< GPIO5 pin index: 24 */
#define BOARD_INITPINS_CAM1_RST_n_PIN_NAME                             CSI0_DAT6   /*!< Pin name */
#define BOARD_INITPINS_CAM1_RST_n_LABEL                             "CAM1_RST_n"   /*!< Label */
#define BOARD_INITPINS_CAM1_RST_n_NAME                              "CAM1_RST_n"   /*!< Identifier name */
#define BOARD_INITPINS_CAM1_RST_n_DIRECTION             kPIN_MUX_DirectionOutput   /*!< Direction */

/* CSI0_DAT7 (coord N3), CAM1_PWDN_n */
#define BOARD_INITPINS_CAM1_PWDN_n_GPIO                                    GPIO5   /*!< GPIO device name: GPIO5 */
#define BOARD_INITPINS_CAM1_PWDN_n_GPIO_PIN                                  25U   /*!< GPIO5 pin index: 25 */
#define BOARD_INITPINS_CAM1_PWDN_n_PIN_NAME                            CSI0_DAT7   /*!< Pin name */
#define BOARD_INITPINS_CAM1_PWDN_n_LABEL                           "CAM1_PWDN_n"   /*!< Label */
#define BOARD_INITPINS_CAM1_PWDN_n_NAME                            "CAM1_PWDN_n"   /*!< Identifier name */
#define BOARD_INITPINS_CAM1_PWDN_n_DIRECTION            kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_16 (coord R2), CAM2_LFLT_n */
#define BOARD_INITPINS_CAM2_LFLT_n_GPIO                                    GPIO7   /*!< GPIO device name: GPIO7 */
#define BOARD_INITPINS_CAM2_LFLT_n_GPIO_PIN                                  11U   /*!< GPIO7 pin index: 11 */
#define BOARD_INITPINS_CAM2_LFLT_n_PIN_NAME                              GPIO_16   /*!< Pin name */
#define BOARD_INITPINS_CAM2_LFLT_n_LABEL                           "CAM2_LFLT_n"   /*!< Label */
#define BOARD_INITPINS_CAM2_LFLT_n_NAME                            "CAM2_LFLT_n"   /*!< Identifier name */
#define BOARD_INITPINS_CAM2_LFLT_n_DIRECTION             kPIN_MUX_DirectionInput   /*!< Direction */

/* GPIO_17 (coord R1), CAM2_RST */
#define BOARD_INITPINS_CAM2_RST_GPIO                                       GPIO7   /*!< GPIO device name: GPIO7 */
#define BOARD_INITPINS_CAM2_RST_GPIO_PIN                                     12U   /*!< GPIO7 pin index: 12 */
#define BOARD_INITPINS_CAM2_RST_PIN_NAME                                 GPIO_17   /*!< Pin name */
#define BOARD_INITPINS_CAM2_RST_LABEL                                 "CAM2_RST"   /*!< Label */
#define BOARD_INITPINS_CAM2_RST_NAME                                  "CAM2_RST"   /*!< Identifier name */
#define BOARD_INITPINS_CAM2_RST_DIRECTION               kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_9 (coord T2), CAM2_LOCK */
#define BOARD_INITPINS_CAM2_LOCK_GPIO                                      GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_CAM2_LOCK_GPIO_PIN                                     9U   /*!< GPIO1 pin index: 9 */
#define BOARD_INITPINS_CAM2_LOCK_PIN_NAME                                 GPIO_9   /*!< Pin name */
#define BOARD_INITPINS_CAM2_LOCK_LABEL                               "CAM2_LOCK"   /*!< Label */
#define BOARD_INITPINS_CAM2_LOCK_NAME                                "CAM2_LOCK"   /*!< Identifier name */
#define BOARD_INITPINS_CAM2_LOCK_DIRECTION               kPIN_MUX_DirectionInput   /*!< Direction */

/* CSI0_DATA_EN (coord P3), CAM2_ENPWR */
#define BOARD_INITPINS_CAM2_ENPWR_GPIO                                     GPIO5   /*!< GPIO device name: GPIO5 */
#define BOARD_INITPINS_CAM2_ENPWR_GPIO_PIN                                   20U   /*!< GPIO5 pin index: 20 */
#define BOARD_INITPINS_CAM2_ENPWR_PIN_NAME                          CSI0_DATA_EN   /*!< Pin name */
#define BOARD_INITPINS_CAM2_ENPWR_LABEL                             "CAM2_ENPWR"   /*!< Label */
#define BOARD_INITPINS_CAM2_ENPWR_NAME                              "CAM2_ENPWR"   /*!< Identifier name */
#define BOARD_INITPINS_CAM2_ENPWR_DIRECTION             kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_3 (coord R7), CPU_ENET_INTn */
#define BOARD_INITPINS_CPU_ENET_INTn_GPIO                                  GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_CPU_ENET_INTn_GPIO_PIN                                 3U   /*!< GPIO1 pin index: 3 */
#define BOARD_INITPINS_CPU_ENET_INTn_PIN_NAME                             GPIO_3   /*!< Pin name */
#define BOARD_INITPINS_CPU_ENET_INTn_LABEL                       "CPU_ENET_INTn"   /*!< Label */
#define BOARD_INITPINS_CPU_ENET_INTn_NAME                        "CPU_ENET_INTn"   /*!< Identifier name */
#define BOARD_INITPINS_CPU_ENET_INTn_DIRECTION           kPIN_MUX_DirectionInput   /*!< Direction */

/* ENET_REF_CLK (coord V22), PHY_RSTn */
#define BOARD_INITPINS_PHY_RSTn_GPIO                                       GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_PHY_RSTn_GPIO_PIN                                     23U   /*!< GPIO1 pin index: 23 */
#define BOARD_INITPINS_PHY_RSTn_PIN_NAME                            ENET_REF_CLK   /*!< Pin name */
#define BOARD_INITPINS_PHY_RSTn_LABEL                                 "PHY_RSTn"   /*!< Label */
#define BOARD_INITPINS_PHY_RSTn_NAME                                  "PHY_RSTn"   /*!< Identifier name */
#define BOARD_INITPINS_PHY_RSTn_DIRECTION               kPIN_MUX_DirectionOutput   /*!< Direction */

/* KEY_ROW4 (coord V5), REMOTE_RST */
#define BOARD_INITPINS_REMOTE_RST_GPIO                                     GPIO4   /*!< GPIO device name: GPIO4 */
#define BOARD_INITPINS_REMOTE_RST_GPIO_PIN                                   15U   /*!< GPIO4 pin index: 15 */
#define BOARD_INITPINS_REMOTE_RST_PIN_NAME                              KEY_ROW4   /*!< Pin name */
#define BOARD_INITPINS_REMOTE_RST_LABEL                             "REMOTE_RST"   /*!< Label */
#define BOARD_INITPINS_REMOTE_RST_NAME                              "REMOTE_RST"   /*!< Identifier name */
#define BOARD_INITPINS_REMOTE_RST_DIRECTION             kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_4 (coord R6), USB_PWREN */
#define BOARD_INITPINS_USB_PWREN_GPIO                                      GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_USB_PWREN_GPIO_PIN                                     4U   /*!< GPIO1 pin index: 4 */
#define BOARD_INITPINS_USB_PWREN_PIN_NAME                                 GPIO_4   /*!< Pin name */
#define BOARD_INITPINS_USB_PWREN_LABEL                               "USB_PWREN"   /*!< Label */
#define BOARD_INITPINS_USB_PWREN_NAME                                "USB_PWREN"   /*!< Identifier name */
#define BOARD_INITPINS_USB_PWREN_DIRECTION              kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_5 (coord R4), USB_RESETn */
#define BOARD_INITPINS_USB_RESETn_GPIO                                     GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_USB_RESETn_GPIO_PIN                                    5U   /*!< GPIO1 pin index: 5 */
#define BOARD_INITPINS_USB_RESETn_PIN_NAME                                GPIO_5   /*!< Pin name */
#define BOARD_INITPINS_USB_RESETn_LABEL                             "USB_RESETn"   /*!< Label */
#define BOARD_INITPINS_USB_RESETn_NAME                              "USB_RESETn"   /*!< Identifier name */
#define BOARD_INITPINS_USB_RESETn_DIRECTION             kPIN_MUX_DirectionOutput   /*!< Direction */

/* KEY_COL4 (coord T6), UX_PWR_EN */
#define BOARD_INITPINS_UX_PWR_EN_GPIO                                      GPIO4   /*!< GPIO device name: GPIO4 */
#define BOARD_INITPINS_UX_PWR_EN_GPIO_PIN                                    14U   /*!< GPIO4 pin index: 14 */
#define BOARD_INITPINS_UX_PWR_EN_PIN_NAME                               KEY_COL4   /*!< Pin name */
#define BOARD_INITPINS_UX_PWR_EN_LABEL                               "UX_PWR_EN"   /*!< Label */
#define BOARD_INITPINS_UX_PWR_EN_NAME                                "UX_PWR_EN"   /*!< Identifier name */
#define BOARD_INITPINS_UX_PWR_EN_DIRECTION              kPIN_MUX_DirectionOutput   /*!< Direction */

/* EIM_D16 (coord C25), UX_5V_OC */
#define BOARD_INITPINS_UX_5V_OC_GPIO                                       GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_UX_5V_OC_GPIO_PIN                                     16U   /*!< GPIO3 pin index: 16 */
#define BOARD_INITPINS_UX_5V_OC_PIN_NAME                                 EIM_D16   /*!< Pin name */
#define BOARD_INITPINS_UX_5V_OC_LABEL                                 "UX_5V_OC"   /*!< Label */
#define BOARD_INITPINS_UX_5V_OC_NAME                                  "UX_5V_OC"   /*!< Identifier name */
#define BOARD_INITPINS_UX_5V_OC_DIRECTION                kPIN_MUX_DirectionInput   /*!< Direction */

/* KEY_COL2 (coord W6), UX_GSTIC_RSTn */
#define BOARD_INITPINS_UX_GSTIC_RSTn_GPIO                                  GPIO4   /*!< GPIO device name: GPIO4 */
#define BOARD_INITPINS_UX_GSTIC_RSTn_GPIO_PIN                                10U   /*!< GPIO4 pin index: 10 */
#define BOARD_INITPINS_UX_GSTIC_RSTn_PIN_NAME                           KEY_COL2   /*!< Pin name */
#define BOARD_INITPINS_UX_GSTIC_RSTn_LABEL                       "UX_GSTIC_RSTn"   /*!< Label */
#define BOARD_INITPINS_UX_GSTIC_RSTn_NAME                        "UX_GSTIC_RSTn"   /*!< Identifier name */
#define BOARD_INITPINS_UX_GSTIC_RSTn_DIRECTION          kPIN_MUX_DirectionOutput   /*!< Direction */

/* KEY_ROW2 (coord W4), UX_GSTIC_TS */
#define BOARD_INITPINS_UX_GSTIC_TS_GPIO                                    GPIO4   /*!< GPIO device name: GPIO4 */
#define BOARD_INITPINS_UX_GSTIC_TS_GPIO_PIN                                  11U   /*!< GPIO4 pin index: 11 */
#define BOARD_INITPINS_UX_GSTIC_TS_PIN_NAME                             KEY_ROW2   /*!< Pin name */
#define BOARD_INITPINS_UX_GSTIC_TS_LABEL                           "UX_GSTIC_TS"   /*!< Label */
#define BOARD_INITPINS_UX_GSTIC_TS_NAME                            "UX_GSTIC_TS"   /*!< Identifier name */
#define BOARD_INITPINS_UX_GSTIC_TS_DIRECTION            kPIN_MUX_DirectionOutput   /*!< Direction */

/* EIM_D25 (coord G22), RS485_DE */
#define BOARD_INITPINS_RS485_DE_GPIO                                       GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_RS485_DE_GPIO_PIN                                     25U   /*!< GPIO3 pin index: 25 */
#define BOARD_INITPINS_RS485_DE_PIN_NAME                                 EIM_D25   /*!< Pin name */
#define BOARD_INITPINS_RS485_DE_LABEL                                 "RS485_DE"   /*!< Label */
#define BOARD_INITPINS_RS485_DE_NAME                                  "RS485_DE"   /*!< Identifier name */
#define BOARD_INITPINS_RS485_DE_DIRECTION               kPIN_MUX_DirectionOutput   /*!< Direction */

/* EIM_D28 (coord G23), RS485_REn */
#define BOARD_INITPINS_RS485_REn_GPIO                                      GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_RS485_REn_GPIO_PIN                                    28U   /*!< GPIO3 pin index: 28 */
#define BOARD_INITPINS_RS485_REn_PIN_NAME                                EIM_D28   /*!< Pin name */
#define BOARD_INITPINS_RS485_REn_LABEL                               "RS485_REn"   /*!< Label */
#define BOARD_INITPINS_RS485_REn_NAME                                "RS485_REn"   /*!< Identifier name */
#define BOARD_INITPINS_RS485_REn_DIRECTION              kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_6 (coord T3), SER_PWR_EN */
#define BOARD_INITPINS_SER_PWR_EN_GPIO                                     GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_SER_PWR_EN_GPIO_PIN                                    6U   /*!< GPIO1 pin index: 6 */
#define BOARD_INITPINS_SER_PWR_EN_PIN_NAME                                GPIO_6   /*!< Pin name */
#define BOARD_INITPINS_SER_PWR_EN_LABEL                             "SER_PWR_EN"   /*!< Label */
#define BOARD_INITPINS_SER_PWR_EN_NAME                              "SER_PWR_EN"   /*!< Identifier name */
#define BOARD_INITPINS_SER_PWR_EN_DIRECTION             kPIN_MUX_DirectionOutput   /*!< Direction */

/* EIM_D19 (coord G21), WIF_PWREN */
#define BOARD_INITPINS_WIF_PWREN_GPIO                                      GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_WIF_PWREN_GPIO_PIN                                    19U   /*!< GPIO3 pin index: 19 */
#define BOARD_INITPINS_WIF_PWREN_PIN_NAME                                EIM_D19   /*!< Pin name */
#define BOARD_INITPINS_WIF_PWREN_LABEL                               "WIF_PWREN"   /*!< Label */
#define BOARD_INITPINS_WIF_PWREN_NAME                                "WIF_PWREN"   /*!< Identifier name */
#define BOARD_INITPINS_WIF_PWREN_DIRECTION              kPIN_MUX_DirectionOutput   /*!< Direction */

/* EIM_D20 (coord G20), WIF_RESETn */
#define BOARD_INITPINS_WIF_RESETn_GPIO                                     GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_WIF_RESETn_GPIO_PIN                                   20U   /*!< GPIO3 pin index: 20 */
#define BOARD_INITPINS_WIF_RESETn_PIN_NAME                               EIM_D20   /*!< Pin name */
#define BOARD_INITPINS_WIF_RESETn_LABEL                             "WIF_RESETn"   /*!< Label */
#define BOARD_INITPINS_WIF_RESETn_NAME                              "WIF_RESETn"   /*!< Identifier name */
#define BOARD_INITPINS_WIF_RESETn_DIRECTION             kPIN_MUX_DirectionOutput   /*!< Direction */

/* EIM_D23 (coord D25), MOD_PWREN */
#define BOARD_INITPINS_MOD_PWREN_GPIO                                      GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_MOD_PWREN_GPIO_PIN                                    23U   /*!< GPIO3 pin index: 23 */
#define BOARD_INITPINS_MOD_PWREN_PIN_NAME                                EIM_D23   /*!< Pin name */
#define BOARD_INITPINS_MOD_PWREN_LABEL                               "MOD_PWREN"   /*!< Label */
#define BOARD_INITPINS_MOD_PWREN_NAME                                "MOD_PWREN"   /*!< Identifier name */
#define BOARD_INITPINS_MOD_PWREN_DIRECTION              kPIN_MUX_DirectionOutput   /*!< Direction */

/* EIM_D24 (coord F22), MOD_RESETn */
#define BOARD_INITPINS_MOD_RESETn_GPIO                                     GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_MOD_RESETn_GPIO_PIN                                   24U   /*!< GPIO3 pin index: 24 */
#define BOARD_INITPINS_MOD_RESETn_PIN_NAME                               EIM_D24   /*!< Pin name */
#define BOARD_INITPINS_MOD_RESETn_LABEL                             "MOD_RESETn"   /*!< Label */
#define BOARD_INITPINS_MOD_RESETn_NAME                              "MOD_RESETn"   /*!< Identifier name */
#define BOARD_INITPINS_MOD_RESETn_DIRECTION             kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_18 (coord P6), MOD_IGTn */
#define BOARD_INITPINS_MOD_IGTn_GPIO                                       GPIO7   /*!< GPIO device name: GPIO7 */
#define BOARD_INITPINS_MOD_IGTn_GPIO_PIN                                     13U   /*!< GPIO7 pin index: 13 */
#define BOARD_INITPINS_MOD_IGTn_PIN_NAME                                 GPIO_18   /*!< Pin name */
#define BOARD_INITPINS_MOD_IGTn_LABEL                                 "MOD_IGTn"   /*!< Label */
#define BOARD_INITPINS_MOD_IGTn_NAME                                  "MOD_IGTn"   /*!< Identifier name */
#define BOARD_INITPINS_MOD_IGTn_DIRECTION               kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_19 (coord P5), MOD_PWRIND */
#define BOARD_INITPINS_MOD_PWRIND_GPIO                                     GPIO4   /*!< GPIO device name: GPIO4 */
#define BOARD_INITPINS_MOD_PWRIND_GPIO_PIN                                    5U   /*!< GPIO4 pin index: 5 */
#define BOARD_INITPINS_MOD_PWRIND_PIN_NAME                               GPIO_19   /*!< Pin name */
#define BOARD_INITPINS_MOD_PWRIND_LABEL                             "MOD_PWRIND"   /*!< Label */
#define BOARD_INITPINS_MOD_PWRIND_NAME                              "MOD_PWRIND"   /*!< Identifier name */
#define BOARD_INITPINS_MOD_PWRIND_DIRECTION              kPIN_MUX_DirectionInput   /*!< Direction */

/* DISP0_DAT9 (coord T25), LCD_3V3_EN */
#define BOARD_INITPINS_LCD_3V3_EN_GPIO                                     GPIO4   /*!< GPIO device name: GPIO4 */
#define BOARD_INITPINS_LCD_3V3_EN_GPIO_PIN                                   30U   /*!< GPIO4 pin index: 30 */
#define BOARD_INITPINS_LCD_3V3_EN_PIN_NAME                            DISP0_DAT9   /*!< Pin name */
#define BOARD_INITPINS_LCD_3V3_EN_LABEL                             "LCD_3V3_EN"   /*!< Label */
#define BOARD_INITPINS_LCD_3V3_EN_NAME                              "LCD_3V3_EN"   /*!< Identifier name */
#define BOARD_INITPINS_LCD_3V3_EN_DIRECTION             kPIN_MUX_DirectionOutput   /*!< Direction */

/* DISP0_DAT0 (coord P24), LCD_BLU_EN */
#define BOARD_INITPINS_LCD_BLU_EN_GPIO                                     GPIO4   /*!< GPIO device name: GPIO4 */
#define BOARD_INITPINS_LCD_BLU_EN_GPIO_PIN                                   21U   /*!< GPIO4 pin index: 21 */
#define BOARD_INITPINS_LCD_BLU_EN_PIN_NAME                            DISP0_DAT0   /*!< Pin name */
#define BOARD_INITPINS_LCD_BLU_EN_LABEL                             "LCD_BLU_EN"   /*!< Label */
#define BOARD_INITPINS_LCD_BLU_EN_NAME                              "LCD_BLU_EN"   /*!< Identifier name */
#define BOARD_INITPINS_LCD_BLU_EN_DIRECTION             kPIN_MUX_DirectionOutput   /*!< Direction */

/* DISP0_DAT1 (coord P22), LCD_REV_SCAN */
#define BOARD_INITPINS_LCD_REV_SCAN_GPIO                                   GPIO4   /*!< GPIO device name: GPIO4 */
#define BOARD_INITPINS_LCD_REV_SCAN_GPIO_PIN                                 22U   /*!< GPIO4 pin index: 22 */
#define BOARD_INITPINS_LCD_REV_SCAN_PIN_NAME                          DISP0_DAT1   /*!< Pin name */
#define BOARD_INITPINS_LCD_REV_SCAN_LABEL                         "LCD_REV_SCAN"   /*!< Label */
#define BOARD_INITPINS_LCD_REV_SCAN_NAME                          "LCD_REV_SCAN"   /*!< Identifier name */
#define BOARD_INITPINS_LCD_REV_SCAN_DIRECTION           kPIN_MUX_DirectionOutput   /*!< Direction */

/* DISP0_DAT2 (coord P23), LCD_SEL_6OR8 */
#define BOARD_INITPINS_LCD_SEL_6OR8_GPIO                                   GPIO4   /*!< GPIO device name: GPIO4 */
#define BOARD_INITPINS_LCD_SEL_6OR8_GPIO_PIN                                 23U   /*!< GPIO4 pin index: 23 */
#define BOARD_INITPINS_LCD_SEL_6OR8_PIN_NAME                          DISP0_DAT2   /*!< Pin name */
#define BOARD_INITPINS_LCD_SEL_6OR8_LABEL                         "LCD_SEL_6OR8"   /*!< Label */
#define BOARD_INITPINS_LCD_SEL_6OR8_NAME                          "LCD_SEL_6OR8"   /*!< Identifier name */
#define BOARD_INITPINS_LCD_SEL_6OR8_DIRECTION           kPIN_MUX_DirectionOutput   /*!< Direction */

/* DISP0_DAT4 (coord P20), SPK_PWREN */
#define BOARD_INITPINS_SPK_PWREN_GPIO                                      GPIO4   /*!< GPIO device name: GPIO4 */
#define BOARD_INITPINS_SPK_PWREN_GPIO_PIN                                    25U   /*!< GPIO4 pin index: 25 */
#define BOARD_INITPINS_SPK_PWREN_PIN_NAME                             DISP0_DAT4   /*!< Pin name */
#define BOARD_INITPINS_SPK_PWREN_LABEL                               "SPK_PWREN"   /*!< Label */
#define BOARD_INITPINS_SPK_PWREN_NAME                                "SPK_PWREN"   /*!< Identifier name */
#define BOARD_INITPINS_SPK_PWREN_DIRECTION              kPIN_MUX_DirectionOutput   /*!< Direction */

/* DISP0_DAT3 (coord P21), USON_PWREN */
#define BOARD_INITPINS_USON_PWREN_GPIO                                     GPIO4   /*!< GPIO device name: GPIO4 */
#define BOARD_INITPINS_USON_PWREN_GPIO_PIN                                   24U   /*!< GPIO4 pin index: 24 */
#define BOARD_INITPINS_USON_PWREN_PIN_NAME                            DISP0_DAT3   /*!< Pin name */
#define BOARD_INITPINS_USON_PWREN_LABEL                             "USON_PWREN"   /*!< Label */
#define BOARD_INITPINS_USON_PWREN_NAME                              "USON_PWREN"   /*!< Identifier name */
#define BOARD_INITPINS_USON_PWREN_DIRECTION             kPIN_MUX_DirectionOutput   /*!< Direction */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                                 /*!< Function assigned for the core: Cortex-A9 (Core #0)[ca9_0] */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
