/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

#include "iMX6DP_registers.h"

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif


/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_0 (coord T5), PM_INT_N */
#define BOARD_INITPINS_PM_INT_N_GPIO                                       GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_PM_INT_N_GPIO_PIN                                      0U   /*!< GPIO1 pin index: 0 */
#define BOARD_INITPINS_PM_INT_N_PIN_NAME                                  GPIO_0   /*!< Pin name */
#define BOARD_INITPINS_PM_INT_N_LABEL                                 "PM_INT_N"   /*!< Label */
#define BOARD_INITPINS_PM_INT_N_NAME                                  "PM_INT_N"   /*!< Identifier name */
#define BOARD_INITPINS_PM_INT_N_DIRECTION                kPIN_MUX_DirectionInput   /*!< Direction */

/* GPIO_2 (coord T1), ETH_PWR_EN */
#define BOARD_INITPINS_ETH_PWR_EN_GPIO                                     GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_ETH_PWR_EN_GPIO_PIN                                    2U   /*!< GPIO1 pin index: 2 */
#define BOARD_INITPINS_ETH_PWR_EN_PIN_NAME                                GPIO_2   /*!< Pin name */
#define BOARD_INITPINS_ETH_PWR_EN_LABEL                             "ETH_PWR_EN"   /*!< Label */
#define BOARD_INITPINS_ETH_PWR_EN_NAME                              "ETH_PWR_EN"   /*!< Identifier name */
#define BOARD_INITPINS_ETH_PWR_EN_DIRECTION             kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_3 (coord R7), PHY_RSTn */
#define BOARD_INITPINS_PHY_RSTn_GPIO                                       GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_PHY_RSTn_GPIO_PIN                                      3U   /*!< GPIO1 pin index: 3 */
#define BOARD_INITPINS_PHY_RSTn_PIN_NAME                                  GPIO_3   /*!< Pin name */
#define BOARD_INITPINS_PHY_RSTn_LABEL                                 "PHY_RSTn"   /*!< Label */
#define BOARD_INITPINS_PHY_RSTn_NAME                                  "PHY_RSTn"   /*!< Identifier name */
#define BOARD_INITPINS_PHY_RSTn_DIRECTION               kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_4 (coord R6), SOC_FLOAT_TRIP1 */
#define BOARD_INITPINS_SOC_FLOAT_TRIP1_GPIO                                GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_SOC_FLOAT_TRIP1_GPIO_PIN                               4U   /*!< GPIO1 pin index: 4 */
#define BOARD_INITPINS_SOC_FLOAT_TRIP1_PIN_NAME                           GPIO_4   /*!< Pin name */
#define BOARD_INITPINS_SOC_FLOAT_TRIP1_LABEL                   "SOC_FLOAT_TRIP1"   /*!< Label */
#define BOARD_INITPINS_SOC_FLOAT_TRIP1_NAME                    "SOC_FLOAT_TRIP1"   /*!< Identifier name */
#define BOARD_INITPINS_SOC_FLOAT_TRIP1_DIRECTION         kPIN_MUX_DirectionInput   /*!< Direction */

/* GPIO_5 (coord R4), SOC_FLOAT_TRIP2 */
#define BOARD_INITPINS_SOC_FLOAT_TRIP2_GPIO                                GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_SOC_FLOAT_TRIP2_GPIO_PIN                               5U   /*!< GPIO1 pin index: 5 */
#define BOARD_INITPINS_SOC_FLOAT_TRIP2_PIN_NAME                           GPIO_5   /*!< Pin name */
#define BOARD_INITPINS_SOC_FLOAT_TRIP2_LABEL                   "SOC_FLOAT_TRIP2"   /*!< Label */
#define BOARD_INITPINS_SOC_FLOAT_TRIP2_NAME                    "SOC_FLOAT_TRIP2"   /*!< Identifier name */
#define BOARD_INITPINS_SOC_FLOAT_TRIP2_DIRECTION         kPIN_MUX_DirectionInput   /*!< Direction */

/* GPIO_6 (coord T3), SER_PWR_EN */
#define BOARD_INITPINS_SER_PWR_EN_GPIO                                     GPIO1   /*!< GPIO device name: GPIO1 */
#define BOARD_INITPINS_SER_PWR_EN_GPIO_PIN                                    6U   /*!< GPIO1 pin index: 6 */
#define BOARD_INITPINS_SER_PWR_EN_PIN_NAME                                GPIO_6   /*!< Pin name */
#define BOARD_INITPINS_SER_PWR_EN_LABEL                             "SER_PWR_EN"   /*!< Label */
#define BOARD_INITPINS_SER_PWR_EN_NAME                              "SER_PWR_EN"   /*!< Identifier name */
#define BOARD_INITPINS_SER_PWR_EN_DIRECTION             kPIN_MUX_DirectionOutput   /*!< Direction */

/* GPIO_16 (coord R2), SOC_REED1 */
#define BOARD_INITPINS_SOC_REED1_GPIO                                      GPIO7   /*!< GPIO device name: GPIO7 */
#define BOARD_INITPINS_SOC_REED1_GPIO_PIN                                    11U   /*!< GPIO7 pin index: 11 */
#define BOARD_INITPINS_SOC_REED1_PIN_NAME                                GPIO_16   /*!< Pin name */
#define BOARD_INITPINS_SOC_REED1_LABEL                               "SOC_REED1"   /*!< Label */
#define BOARD_INITPINS_SOC_REED1_NAME                                "SOC_REED1"   /*!< Identifier name */
#define BOARD_INITPINS_SOC_REED1_DIRECTION               kPIN_MUX_DirectionInput   /*!< Direction */

/* GPIO_17 (coord R1), SOC_REED2 */
#define BOARD_INITPINS_SOC_REED2_GPIO                                      GPIO7   /*!< GPIO device name: GPIO7 */
#define BOARD_INITPINS_SOC_REED2_GPIO_PIN                                    12U   /*!< GPIO7 pin index: 12 */
#define BOARD_INITPINS_SOC_REED2_PIN_NAME                                GPIO_17   /*!< Pin name */
#define BOARD_INITPINS_SOC_REED2_LABEL                               "SOC_REED2"   /*!< Label */
#define BOARD_INITPINS_SOC_REED2_NAME                                "SOC_REED2"   /*!< Identifier name */
#define BOARD_INITPINS_SOC_REED2_DIRECTION               kPIN_MUX_DirectionInput   /*!< Direction */

/* GPIO_18 (coord P6), SOC_REED3 */
#define BOARD_INITPINS_SOC_REED3_GPIO                                      GPIO7   /*!< GPIO device name: GPIO7 */
#define BOARD_INITPINS_SOC_REED3_GPIO_PIN                                    13U   /*!< GPIO7 pin index: 13 */
#define BOARD_INITPINS_SOC_REED3_PIN_NAME                                GPIO_18   /*!< Pin name */
#define BOARD_INITPINS_SOC_REED3_LABEL                               "SOC_REED3"   /*!< Label */
#define BOARD_INITPINS_SOC_REED3_NAME                                "SOC_REED3"   /*!< Identifier name */
#define BOARD_INITPINS_SOC_REED3_DIRECTION               kPIN_MUX_DirectionInput   /*!< Direction */

/* GPIO_19 (coord P5), SOC_REED4 */
#define BOARD_INITPINS_SOC_REED4_GPIO                                      GPIO4   /*!< GPIO device name: GPIO4 */
#define BOARD_INITPINS_SOC_REED4_GPIO_PIN                                     5U   /*!< GPIO4 pin index: 5 */
#define BOARD_INITPINS_SOC_REED4_PIN_NAME                                GPIO_19   /*!< Pin name */
#define BOARD_INITPINS_SOC_REED4_LABEL                               "SOC_REED4"   /*!< Label */
#define BOARD_INITPINS_SOC_REED4_NAME                                "SOC_REED4"   /*!< Identifier name */
#define BOARD_INITPINS_SOC_REED4_DIRECTION               kPIN_MUX_DirectionInput   /*!< Direction */

/* NANDF_CS0 (coord F15), ACCEL_INT_B */
#define BOARD_INITPINS_ACCEL_INT_B_GPIO                                    GPIO6   /*!< GPIO device name: GPIO6 */
#define BOARD_INITPINS_ACCEL_INT_B_GPIO_PIN                                  11U   /*!< GPIO6 pin index: 11 */
#define BOARD_INITPINS_ACCEL_INT_B_PIN_NAME                            NANDF_CS0   /*!< Pin name */
#define BOARD_INITPINS_ACCEL_INT_B_LABEL                           "ACCEL_INT_B"   /*!< Label */
#define BOARD_INITPINS_ACCEL_INT_B_NAME                            "ACCEL_INT_B"   /*!< Identifier name */
#define BOARD_INITPINS_ACCEL_INT_B_DIRECTION             kPIN_MUX_DirectionInput   /*!< Direction */

/* NANDF_CS1 (coord C16), MAG_INT_B */
#define BOARD_INITPINS_MAG_INT_B_GPIO                                      GPIO6   /*!< GPIO device name: GPIO6 */
#define BOARD_INITPINS_MAG_INT_B_GPIO_PIN                                    14U   /*!< GPIO6 pin index: 14 */
#define BOARD_INITPINS_MAG_INT_B_PIN_NAME                              NANDF_CS1   /*!< Pin name */
#define BOARD_INITPINS_MAG_INT_B_LABEL                               "MAG_INT_B"   /*!< Label */
#define BOARD_INITPINS_MAG_INT_B_NAME                                "MAG_INT_B"   /*!< Identifier name */
#define BOARD_INITPINS_MAG_INT_B_DIRECTION               kPIN_MUX_DirectionInput   /*!< Direction */

/* NANDF_CS2 (coord A17), MAG_DRDY */
#define BOARD_INITPINS_MAG_DRDY_GPIO                                       GPIO6   /*!< GPIO device name: GPIO6 */
#define BOARD_INITPINS_MAG_DRDY_GPIO_PIN                                     15U   /*!< GPIO6 pin index: 15 */
#define BOARD_INITPINS_MAG_DRDY_PIN_NAME                               NANDF_CS2   /*!< Pin name */
#define BOARD_INITPINS_MAG_DRDY_LABEL                                 "MAG_DRDY"   /*!< Label */
#define BOARD_INITPINS_MAG_DRDY_NAME                                  "MAG_DRDY"   /*!< Identifier name */
#define BOARD_INITPINS_MAG_DRDY_DIRECTION                kPIN_MUX_DirectionInput   /*!< Direction */

/* NANDF_CLE (coord C15), SOC_SURGE_DET2 */
#define BOARD_INITPINS_SOC_SURGE_DET2_GPIO                                 GPIO6   /*!< GPIO device name: GPIO6 */
#define BOARD_INITPINS_SOC_SURGE_DET2_GPIO_PIN                                7U   /*!< GPIO6 pin index: 7 */
#define BOARD_INITPINS_SOC_SURGE_DET2_PIN_NAME                         NANDF_CLE   /*!< Pin name */
#define BOARD_INITPINS_SOC_SURGE_DET2_LABEL                     "SOC_SURGE_DET2"   /*!< Label */
#define BOARD_INITPINS_SOC_SURGE_DET2_NAME                      "SOC_SURGE_DET2"   /*!< Identifier name */
#define BOARD_INITPINS_SOC_SURGE_DET2_DIRECTION          kPIN_MUX_DirectionInput   /*!< Direction */

/* NANDF_ALE (coord A16), SOC_SURGE_DET1 */
#define BOARD_INITPINS_SOC_SURGE_DET1_GPIO                                 GPIO6   /*!< GPIO device name: GPIO6 */
#define BOARD_INITPINS_SOC_SURGE_DET1_GPIO_PIN                                8U   /*!< GPIO6 pin index: 8 */
#define BOARD_INITPINS_SOC_SURGE_DET1_PIN_NAME                         NANDF_ALE   /*!< Pin name */
#define BOARD_INITPINS_SOC_SURGE_DET1_LABEL                     "SOC_SURGE_DET1"   /*!< Label */
#define BOARD_INITPINS_SOC_SURGE_DET1_NAME                      "SOC_SURGE_DET1"   /*!< Identifier name */
#define BOARD_INITPINS_SOC_SURGE_DET1_DIRECTION          kPIN_MUX_DirectionInput   /*!< Direction */

/* NANDF_WP_B (coord E15), SOC_SURGE_DET3 */
#define BOARD_INITPINS_SOC_SURGE_DET3_GPIO                                 GPIO6   /*!< GPIO device name: GPIO6 */
#define BOARD_INITPINS_SOC_SURGE_DET3_GPIO_PIN                                9U   /*!< GPIO6 pin index: 9 */
#define BOARD_INITPINS_SOC_SURGE_DET3_PIN_NAME                        NANDF_WP_B   /*!< Pin name */
#define BOARD_INITPINS_SOC_SURGE_DET3_LABEL                     "SOC_SURGE_DET3"   /*!< Label */
#define BOARD_INITPINS_SOC_SURGE_DET3_NAME                      "SOC_SURGE_DET3"   /*!< Identifier name */
#define BOARD_INITPINS_SOC_SURGE_DET3_DIRECTION          kPIN_MUX_DirectionInput   /*!< Direction */

/* NANDF_RB0 (coord B16), SOC_SURGE_DET4 */
#define BOARD_INITPINS_SOC_SURGE_DET4_GPIO                                 GPIO6   /*!< GPIO device name: GPIO6 */
#define BOARD_INITPINS_SOC_SURGE_DET4_GPIO_PIN                               10U   /*!< GPIO6 pin index: 10 */
#define BOARD_INITPINS_SOC_SURGE_DET4_PIN_NAME                         NANDF_RB0   /*!< Pin name */
#define BOARD_INITPINS_SOC_SURGE_DET4_LABEL                     "SOC_SURGE_DET4"   /*!< Label */
#define BOARD_INITPINS_SOC_SURGE_DET4_NAME                      "SOC_SURGE_DET4"   /*!< Identifier name */
#define BOARD_INITPINS_SOC_SURGE_DET4_DIRECTION          kPIN_MUX_DirectionInput   /*!< Direction */

/* NANDF_D0 (coord A18), GPIO2_0 */
#define BOARD_INITPINS_GPIO2_0_GPIO                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_GPIO2_0_GPIO_PIN                                       0U   /*!< GPIO2 pin index: 0 */
#define BOARD_INITPINS_GPIO2_0_PIN_NAME                                 NANDF_D0   /*!< Pin name */
#define BOARD_INITPINS_GPIO2_0_LABEL                                   "GPIO2_0"   /*!< Label */
#define BOARD_INITPINS_GPIO2_0_NAME                                    "GPIO2_0"   /*!< Identifier name */
#define BOARD_INITPINS_GPIO2_0_DIRECTION                kPIN_MUX_DirectionOutput   /*!< Direction */

/* NANDF_D1 (coord C17), GPIO2_1 */
#define BOARD_INITPINS_GPIO2_1_GPIO                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_GPIO2_1_GPIO_PIN                                       1U   /*!< GPIO2 pin index: 1 */
#define BOARD_INITPINS_GPIO2_1_PIN_NAME                                 NANDF_D1   /*!< Pin name */
#define BOARD_INITPINS_GPIO2_1_LABEL                                   "GPIO2_1"   /*!< Label */
#define BOARD_INITPINS_GPIO2_1_NAME                                    "GPIO2_1"   /*!< Identifier name */
#define BOARD_INITPINS_GPIO2_1_DIRECTION                kPIN_MUX_DirectionOutput   /*!< Direction */

/* NANDF_D2 (coord F16), GPIO2_2 */
#define BOARD_INITPINS_GPIO2_2_GPIO                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_GPIO2_2_GPIO_PIN                                       2U   /*!< GPIO2 pin index: 2 */
#define BOARD_INITPINS_GPIO2_2_PIN_NAME                                 NANDF_D2   /*!< Pin name */
#define BOARD_INITPINS_GPIO2_2_LABEL                                   "GPIO2_2"   /*!< Label */
#define BOARD_INITPINS_GPIO2_2_NAME                                    "GPIO2_2"   /*!< Identifier name */
#define BOARD_INITPINS_GPIO2_2_DIRECTION                kPIN_MUX_DirectionOutput   /*!< Direction */

/* NANDF_D3 (coord D17), GPIO2_3 */
#define BOARD_INITPINS_GPIO2_3_GPIO                                        GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_GPIO2_3_GPIO_PIN                                       3U   /*!< GPIO2 pin index: 3 */
#define BOARD_INITPINS_GPIO2_3_PIN_NAME                                 NANDF_D3   /*!< Pin name */
#define BOARD_INITPINS_GPIO2_3_LABEL                                   "GPIO2_3"   /*!< Label */
#define BOARD_INITPINS_GPIO2_3_NAME                                    "GPIO2_3"   /*!< Identifier name */
#define BOARD_INITPINS_GPIO2_3_DIRECTION                kPIN_MUX_DirectionOutput   /*!< Direction */

/* NANDF_D4 (coord A19), SOC_SURGE_DET5 */
#define BOARD_INITPINS_SOC_SURGE_DET5_GPIO                                 GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_SOC_SURGE_DET5_GPIO_PIN                                4U   /*!< GPIO2 pin index: 4 */
#define BOARD_INITPINS_SOC_SURGE_DET5_PIN_NAME                          NANDF_D4   /*!< Pin name */
#define BOARD_INITPINS_SOC_SURGE_DET5_LABEL                     "SOC_SURGE_DET5"   /*!< Label */
#define BOARD_INITPINS_SOC_SURGE_DET5_NAME                      "SOC_SURGE_DET5"   /*!< Identifier name */
#define BOARD_INITPINS_SOC_SURGE_DET5_DIRECTION          kPIN_MUX_DirectionInput   /*!< Direction */

/* NANDF_D6 (coord E17), PS2SOC_PG */
#define BOARD_INITPINS_PS2SOC_PG_GPIO                                      GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_PS2SOC_PG_GPIO_PIN                                     6U   /*!< GPIO2 pin index: 6 */
#define BOARD_INITPINS_PS2SOC_PG_PIN_NAME                               NANDF_D6   /*!< Pin name */
#define BOARD_INITPINS_PS2SOC_PG_LABEL                               "PS2SOC_PG"   /*!< Label */
#define BOARD_INITPINS_PS2SOC_PG_NAME                                "PS2SOC_PG"   /*!< Identifier name */
#define BOARD_INITPINS_PS2SOC_PG_DIRECTION               kPIN_MUX_DirectionInput   /*!< Direction */

/* SD4_DAT4 (coord E18), FAN1_SP_CTRL */
#define BOARD_INITPINS_FAN1_SP_CTRL_GPIO                                   GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_FAN1_SP_CTRL_GPIO_PIN                                 12U   /*!< GPIO2 pin index: 12 */
#define BOARD_INITPINS_FAN1_SP_CTRL_PIN_NAME                            SD4_DAT4   /*!< Pin name */
#define BOARD_INITPINS_FAN1_SP_CTRL_LABEL                         "FAN1_SP_CTRL"   /*!< Label */
#define BOARD_INITPINS_FAN1_SP_CTRL_NAME                          "FAN1_SP_CTRL"   /*!< Identifier name */
#define BOARD_INITPINS_FAN1_SP_CTRL_DIRECTION           kPIN_MUX_DirectionOutput   /*!< Direction */

/* SD4_DAT5 (coord C19), FAN2_SP_CTRL */
#define BOARD_INITPINS_FAN2_SP_CTRL_GPIO                                   GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_FAN2_SP_CTRL_GPIO_PIN                                 13U   /*!< GPIO2 pin index: 13 */
#define BOARD_INITPINS_FAN2_SP_CTRL_PIN_NAME                            SD4_DAT5   /*!< Pin name */
#define BOARD_INITPINS_FAN2_SP_CTRL_LABEL                         "FAN2_SP_CTRL"   /*!< Label */
#define BOARD_INITPINS_FAN2_SP_CTRL_NAME                          "FAN2_SP_CTRL"   /*!< Identifier name */
#define BOARD_INITPINS_FAN2_SP_CTRL_DIRECTION           kPIN_MUX_DirectionOutput   /*!< Direction */

/* SD4_DAT6 (coord B20), FAN_TACH_DSP0 */
#define BOARD_INITPINS_FAN_TACH_DSP0_GPIO                                  GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_FAN_TACH_DSP0_GPIO_PIN                                14U   /*!< GPIO2 pin index: 14 */
#define BOARD_INITPINS_FAN_TACH_DSP0_PIN_NAME                           SD4_DAT6   /*!< Pin name */
#define BOARD_INITPINS_FAN_TACH_DSP0_LABEL                       "FAN_TACH_DSP0"   /*!< Label */
#define BOARD_INITPINS_FAN_TACH_DSP0_NAME                        "FAN_TACH_DSP0"   /*!< Identifier name */
#define BOARD_INITPINS_FAN_TACH_DSP0_DIRECTION           kPIN_MUX_DirectionInput   /*!< Direction */

/* SD4_DAT7 (coord D19), FAN_TACH_DSP1 */
#define BOARD_INITPINS_FAN_TACH_DSP1_GPIO                                  GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_FAN_TACH_DSP1_GPIO_PIN                                15U   /*!< GPIO2 pin index: 15 */
#define BOARD_INITPINS_FAN_TACH_DSP1_PIN_NAME                           SD4_DAT7   /*!< Pin name */
#define BOARD_INITPINS_FAN_TACH_DSP1_LABEL                       "FAN_TACH_DSP1"   /*!< Label */
#define BOARD_INITPINS_FAN_TACH_DSP1_NAME                        "FAN_TACH_DSP1"   /*!< Identifier name */
#define BOARD_INITPINS_FAN_TACH_DSP1_DIRECTION           kPIN_MUX_DirectionInput   /*!< Direction */

/* EIM_D16 (coord C25), RTD_DRDYn */
#define BOARD_INITPINS_RTD_DRDYn_GPIO                                      GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_RTD_DRDYn_GPIO_PIN                                    16U   /*!< GPIO3 pin index: 16 */
#define BOARD_INITPINS_RTD_DRDYn_PIN_NAME                                EIM_D16   /*!< Pin name */
#define BOARD_INITPINS_RTD_DRDYn_LABEL                               "RTD_DRDYn"   /*!< Label */
#define BOARD_INITPINS_RTD_DRDYn_NAME                                "RTD_DRDYn"   /*!< Identifier name */
#define BOARD_INITPINS_RTD_DRDYn_DIRECTION               kPIN_MUX_DirectionInput   /*!< Direction */

/* EIM_D19 (coord G21), RTD_START_SYNC */
#define BOARD_INITPINS_RTD_START_SYNC_GPIO                                 GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_RTD_START_SYNC_GPIO_PIN                               19U   /*!< GPIO3 pin index: 19 */
#define BOARD_INITPINS_RTD_START_SYNC_PIN_NAME                           EIM_D19   /*!< Pin name */
#define BOARD_INITPINS_RTD_START_SYNC_LABEL                     "RTD_START_SYNC"   /*!< Label */
#define BOARD_INITPINS_RTD_START_SYNC_NAME                      "RTD_START_SYNC"   /*!< Identifier name */
#define BOARD_INITPINS_RTD_START_SYNC_DIRECTION         kPIN_MUX_DirectionOutput   /*!< Direction */

/* EIM_D20 (coord G20), PM_RESET_N */
#define BOARD_INITPINS_PM_RESET_N_GPIO                                     GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_PM_RESET_N_GPIO_PIN                                   20U   /*!< GPIO3 pin index: 20 */
#define BOARD_INITPINS_PM_RESET_N_PIN_NAME                               EIM_D20   /*!< Pin name */
#define BOARD_INITPINS_PM_RESET_N_LABEL                             "PM_RESET_N"   /*!< Label */
#define BOARD_INITPINS_PM_RESET_N_NAME                              "PM_RESET_N"   /*!< Identifier name */
#define BOARD_INITPINS_PM_RESET_N_DIRECTION             kPIN_MUX_DirectionOutput   /*!< Direction */

/* EIM_D23 (coord D25), SOC_THER_SW1 */
#define BOARD_INITPINS_SOC_THER_SW1_GPIO                                   GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_SOC_THER_SW1_GPIO_PIN                                 23U   /*!< GPIO3 pin index: 23 */
#define BOARD_INITPINS_SOC_THER_SW1_PIN_NAME                             EIM_D23   /*!< Pin name */
#define BOARD_INITPINS_SOC_THER_SW1_LABEL                         "SOC_THER_SW1"   /*!< Label */
#define BOARD_INITPINS_SOC_THER_SW1_NAME                          "SOC_THER_SW1"   /*!< Identifier name */
#define BOARD_INITPINS_SOC_THER_SW1_DIRECTION            kPIN_MUX_DirectionInput   /*!< Direction */

/* EIM_D24 (coord F22), SOC_THER_SW2 */
#define BOARD_INITPINS_SOC_THER_SW2_GPIO                                   GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_SOC_THER_SW2_GPIO_PIN                                 24U   /*!< GPIO3 pin index: 24 */
#define BOARD_INITPINS_SOC_THER_SW2_PIN_NAME                             EIM_D24   /*!< Pin name */
#define BOARD_INITPINS_SOC_THER_SW2_LABEL                         "SOC_THER_SW2"   /*!< Label */
#define BOARD_INITPINS_SOC_THER_SW2_NAME                          "SOC_THER_SW2"   /*!< Identifier name */
#define BOARD_INITPINS_SOC_THER_SW2_DIRECTION            kPIN_MUX_DirectionInput   /*!< Direction */

/* EIM_D30 (coord J20), SOC_THER_SW3 */
#define BOARD_INITPINS_SOC_THER_SW3_GPIO                                   GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_SOC_THER_SW3_GPIO_PIN                                 30U   /*!< GPIO3 pin index: 30 */
#define BOARD_INITPINS_SOC_THER_SW3_PIN_NAME                             EIM_D30   /*!< Pin name */
#define BOARD_INITPINS_SOC_THER_SW3_LABEL                         "SOC_THER_SW3"   /*!< Label */
#define BOARD_INITPINS_SOC_THER_SW3_NAME                          "SOC_THER_SW3"   /*!< Identifier name */
#define BOARD_INITPINS_SOC_THER_SW3_DIRECTION            kPIN_MUX_DirectionInput   /*!< Direction */

/* EIM_D31 (coord H21), SOC_THER_SW4 */
#define BOARD_INITPINS_SOC_THER_SW4_GPIO                                   GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_SOC_THER_SW4_GPIO_PIN                                 31U   /*!< GPIO3 pin index: 31 */
#define BOARD_INITPINS_SOC_THER_SW4_PIN_NAME                             EIM_D31   /*!< Pin name */
#define BOARD_INITPINS_SOC_THER_SW4_LABEL                         "SOC_THER_SW4"   /*!< Label */
#define BOARD_INITPINS_SOC_THER_SW4_NAME                          "SOC_THER_SW4"   /*!< Identifier name */
#define BOARD_INITPINS_SOC_THER_SW4_DIRECTION            kPIN_MUX_DirectionInput   /*!< Direction */

/* EIM_D29 (coord J19), PMIC_INT_B */
#define BOARD_INITPINS_PMIC_INT_B_GPIO                                     GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_PMIC_INT_B_GPIO_PIN                                   29U   /*!< GPIO3 pin index: 29 */
#define BOARD_INITPINS_PMIC_INT_B_PIN_NAME                               EIM_D29   /*!< Pin name */
#define BOARD_INITPINS_PMIC_INT_B_LABEL                             "PMIC_INT_B"   /*!< Label */
#define BOARD_INITPINS_PMIC_INT_B_NAME                              "PMIC_INT_B"   /*!< Identifier name */
#define BOARD_INITPINS_PMIC_INT_B_DIRECTION              kPIN_MUX_DirectionInput   /*!< Direction */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                                 /*!< Function assigned for the core: Cortex-A9 (Core #0)[ca9_0] */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
